services:
  api:
    build: .
    restart: unless-stopped
    command: "gunicorn -w 2 -k uvicorn.workers.UvicornWorker -b 0.0.0.0:8000 --timeout 300 --name farmsubsidy_api \
      --log-level info --log-file - farmsubsidy_store.api:app"
    volumes:
      - ${DATA_ROOT:-.}/logs/gunicorn-api:/var/log
    ports:
      - 127.0.0.1:8000:8000
    links:
      - clickhouse
      - redis
    environment:
      DATABASE_URI: clickhouse
      REDIS_URL: redis://redis
      API_CACHE: 1
      API_ALLOWED_ORIGIN: ${API_ALLOWED_ORIGIN:-https://sql.farmsubsidy.org}
      API_KEY: ${API_KEY}

  clickhouse:
    image: clickhouse/clickhouse-server
    restart: unless-stopped
    volumes:
      - ${DATA_ROOT:-.}/clickhouse-data:/var/lib/clickhouse
      - ${DATA_ROOT:-.}/logs/clickhouse:/var/log/clickhouse-server
    ports:
      - 127.0.0.1:9000:9000
      - 127.0.0.1:8123:8123
    ulimits:
      nofile:
        soft: "65536"
        hard: "65536"

  redis:
    image: redis:alpine
    restart: unless-stopped
    ports:
      - 127.0.0.1:6379:6379
